### ISSUE TITLE
Status dashboard redirects elsewhere?

### ISSUE THREAD

**Issue by wdhdev** [DOT-furry-dev-ru/register#1]
Your status dashboard link redirects to www.is-a.dev, is that intended? 😉

**Comment by furyashnyy** [comment]
Yes, this is done on purpose, but the site will be www.furry-dev.ru completely redesigned, so far it works and OK, but I'll make a new site from scratch (www.furry-dev.ru)

**Comment by furyashnyy** [comment]
⠀

**Comment by furyashnyy** [comment]
So far, I have not had time to change everything and so far it will be, I will fix everything soon

**Comment by furyashnyy** [comment]
So far, I haven't had time to change everything, and probably somewhere in the code everything is going to is-a.dev

**Comment by furyashnyy** [comment]
I will try to find the problem and fix it

**Comment by wdhdev** [comment]
It's because you pointed the status dashboard to my domain 😆

**Comment by furyashnyy** [comment]
Sorry😆 I'll fix it soon (there's no way yet since I'm not at home and a little busy)
